apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::762107918466:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5SDJCTPINIPX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::762107918466:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-29T18:53:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1844"
  uid: 5d530fab-cbd1-4998-a465-541c25cb8697
